create table public.tree_types (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  baumart_bo character varying null,
  description text null,
  constraint tree_types_pkey primary key (id)
) TABLESPACE pg_default;