-- Tabelle zur Beschreibung von Baumarten (botanisch: "species")
create table public.tree_species (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),

  -- Botanischer Name, identisch zu `tree_type_botanic` aus der `trees`-Tabelle
  tree_type_botanic varchar not null,

  description_emotional text,
  description_neutral text
);

-- Jede Art darf nur einmal vorkommen
create unique index on public.tree_species (tree_type_botanic);