/**
 * Minimal Markdown parser to safely render formatted chat messages.
 * 
 * Supports:
 * - **bold** → <strong>
 * - _italic_ → <em>
 * - \n → <br>
 * 
 * Security:
 * - Escapes &, <, > to prevent raw HTML execution (e.g. <script> tags)
 * - Allows only safe inline tags generated by regex replacements
 * - Use with {@html ...} ONLY IF the input is properly escaped first (as done here)
 */
export function parseMarkdown(input: string): string {
    return input
      // Escape HTML special characters to prevent XSS
      .replace(/&/g, '&amp;') // must come first
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      // Parse basic markdown syntax
      .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>') // bold
      .replace(/_(.+?)_/g, '<em>$1</em>')               // italic
      .replace(/\n/g, '<br>');                          // line breaks
  }  